FROM yavalek/drjack-wrf3:latest

ENV BASEDIR=/root/rasp
ENV SITENAME=SASK
ENV PATH="${BASEDIR}/bin:${PATH}"

WORKDIR /root/rasp

COPY ${SITENAME} ${BASEDIR}/${SITENAME}
COPY rasp.region_data.ncl ${BASEDIR}/GM/
COPY rasp.site.runenvironment ${BASEDIR}/

VOLUME ["/root/rasp/${SITENAME}/OUT/", "/root/rasp/${SITENAME}/LOG/"]

CMD ["runGM", "SASK"]
